---
ansible_python_interpreter: /usr/bin/python3

# Do we want check connection to the test VM? network might be blocked from FE
test_vm_check_connection: false

execute_storage_benchmarking: false

create_test_network: false
# Vars for the test network
test_vnet_name: 'vxlan'

# Marketplace App name for test VM instantiation
test_vm_name: 'Alpine Linux 3.21 (aarch64)'

test_vm_template_extra: |
  CPU_MODEL=[
    MODEL="host-passthrough" ]

# Connectivity matrix test's parameters
conn_matrix_bridge_name: br1
conn_matrix_ping_count: 10
conn_matrix_vnet_name: vxlan
