---
ansible_python_interpreter: /usr/bin/python3

validation:
  create_vnet: false
  conn_matrix:
    bridge_name: br1
    vnet_name: vxlan
  vm:
    check_connection: false
    market_name: 'Alpine Linux 3.21 (aarch64)'
    template_extra: |
      CPU_MODEL=[
        MODEL="host-passthrough" ]
  run_storage_benchmark: false
